// Bundled lessons work offline; learning-tools adds optional cloud services.
const $=s=>document.querySelector(s),icon=n=>`<i data-lucide="${n}"></i>`;
const photos={de:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1100&q=85',en:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1100&q=85'};
const lessons={de:{name:'德语',native:'DEUTSCH',level:'A1 → B1',title:'Ein Morgen in den Bergen',subtitle:'山间的一个清晨',category:'生活故事',time:'约 15 分钟',lang:'de-DE',voice:'标准德语',words:'126',sentences:['Heute steht Lena früh auf.','Sie wohnt in einem kleinen Dorf in den Bergen.','Am Morgen öffnet sie das Fenster. Die Luft ist frisch.','Nach dem Frühstück geht sie nach draußen.','Sie nimmt ihren Rucksack mit und geht zum See.','Am See sitzt sie auf einer Bank. Sie hört die Vögel und trinkt einen Tee.','Heute hat Lena Zeit. Sie bleibt noch ein bisschen.'],marked:{1:'Bergen',2:'frisch',4:'Rucksack'},word:{Bergen:['der Berg · 名词 · 阳性','/bɛʁk/','山；这里的 den Bergen 是复数第三格。','复数：die Berge','Die Berge sind sehr schön.','这些山很美。'],frisch:['形容词','/fʁɪʃ/','清新的；这里指空气清新。','原形：frisch','Die Luft ist frisch.','空气很清新。'],Rucksack:['der Rucksack · 名词 · 阳性','/ˈʁʊkzak/','背包；句中是第四格宾语。','复数：die Rucksäcke','Mein Rucksack ist klein.','我的背包很小。']}},en:{name:'英语',native:'ENGLISH',level:'B2 → C1',title:'The Quiet Value of Urban Trees',subtitle:'城市树木，安静而重要的存在',category:'环境与生活',time:'约 15 分钟',lang:'en-GB',voice:'英式英语',words:'142',sentences:['A city can feel entirely different beneath a canopy of trees.','Beyond their obvious beauty, urban trees provide something increasingly scarce: a place to slow down.','Their shade makes a crowded pavement feel more welcoming, while their leaves soften the outline of buildings.','Yet a greener city does not appear overnight. It requires patience, careful planning and sustained attention.','Planting a tree is only the beginning; keeping it healthy is a commitment that extends across generations.','Perhaps the most valuable thing trees offer is a reminder that progress need not always be immediate.'],marked:{0:'canopy',1:'scarce',3:'sustained'},word:{canopy:['noun · 名词','/ˈkænəpi/','树冠层；这里指树木形成的遮蔽空间。','复数：canopies','We walked beneath the leafy canopy.','我们在枝叶形成的树荫下行走。'],scarce:['adjective · 形容词','/skeəs/','稀缺的；这里形容可以放慢节奏的空间越来越少。','搭配：increasingly scarce','Quiet spaces are scarce in the city.','城市里安静的空间很少。'],sustained:['adjective · 形容词','/səˈsteɪnd/','持续的；强调关注需要长期维持。','词源：sustain','The project needs sustained attention.','这个项目需要持续关注。']}}};
let page='home',language='de',saved=new Map(JSON.parse(localStorage.getItem('daily-page-vocab')||'[]')),playing=false,sentenceIndex=0,toastTimer,activeTab='structure';
const navItems=[['home','house','今日'],['vocabulary','bookmark','生词'],['settings','sliders-horizontal','设置']];
function icons(){if(window.lucide)lucide.createIcons()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3500)}
function navigation(){const html=navItems.map(([id,ico,label])=>`<button data-nav="${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${icon(ico)}<span>${label}${id==='vocabulary'&&saved.size?' · '+saved.size:''}</span></button>`).join('');$('.nav').innerHTML=html;$('.mobile-nav').innerHTML=html;$('.mobile-nav').classList.toggle('hidden',page==='reader');$('#audio').classList.toggle('hidden',page!=='reader')}
function lessonCard(id){const l=lessons[id];return `<article class="lesson"><img class="lesson-photo ${id==='en'?'english':''}" src="${photos[id]}" alt="${id==='de'?'清晨阳光下的山峦':'阳光穿过绿色树林'}"><div class="lesson-body"><div class="row between"><div class="row language">${l.native}<span class="level">${l.level}</span></div><span class="tag">${l.category}</span></div><h3>${l.title}</h3><p class="lesson-desc">${l.subtitle}</p><div class="row meta"><span class="row">${icon('clock-3')}${l.time}</span><span class="row">${icon('headphones')}${l.voice}</span><span>阅读 · 练习 · 跟读</span></div><div class="lesson-footer"><button class="primary" data-read="${id}">开始${l.name}学习 ${icon('arrow-right')}</button></div></div></article>`}
function home(){return `<div class="row between greeting"><div><div class="eyebrow">YOUR DAILY CHAPTER</div><h1>给自己，一页的时间。</h1><p>读一点世界，让语言慢慢成为日常。</p></div><div class="streak">${icon('sprout')}今天，从这里开始</div></div><div class="row between section-head"><h2>今日学习</h2><span class="muted"><small>两种语言，各 15 分钟</small></span></div><div class="today-grid">${lessonCard('de')}${lessonCard('en')}</div><div class="below"><section class="review-section"><div class="row between"><h2>把新词，变成熟悉的词。</h2>${icon('bookmark')}</div><p class="muted" style="font-size:13px;margin-top:8px">今天遇见的词，会在之后的阅读里再见。</p><div class="word-preview"><span class="word-chip">frisch</span><span class="word-chip">canopy</span><span class="word-chip">sustained</span></div><button class="text-btn" data-nav="vocabulary">我的生词 ${icon('arrow-up-right')}</button></section><section class="review-section"><div class="row between"><h2>本周足迹</h2><small class="muted">新的开始</small></div><div class="week">${['一','二','三','四','五','六','日'].map((d,i)=>`<div class="day ${i===(new Date().getDay()+6)%7?'now':''}"><small>${d}</small><span>${i===(new Date().getDay()+6)%7?'·':'—'}</span></div>`).join('')}</div></section></div>`}
function reader(){const l=lessons[language];return `<div class="reader-layout"><div class="row between reader-toolbar"><button class="text-btn" data-nav="home">${icon('arrow-left')}今日学习</button><div class="segmented" aria-label="学习语言"><button data-read="de" class="${language==='de'?'active':''}">德语</button><button data-read="en" class="${language==='en'?'active':''}">英语</button></div></div><header class="article-head"><div class="row between"><span class="eyebrow" style="margin:0">${l.native} / ${l.level.split(' → ')[0]}</span><span class="tag">${l.category}</span></div><h1>${l.title}</h1><p class="article-subtitle">${l.subtitle}</p><div class="row article-meta"><span>原创短文</span><span>阅读约 ${language==='de'?'5':'6'} 分钟</span><span class="row">${icon('headphones')}${l.voice}</span></div></header><img class="article-photo" src="${photos[language]}" alt="${l.subtitle}"><div class="article-text">${l.sentences.map((s,i)=>`<p class="sentence-row" data-sentence="${i}"><span>${l.marked[i]?s.replace(l.marked[i],`<button class="word" data-word="${l.marked[i]}" aria-label="解释 ${l.marked[i]}">${l.marked[i]}</button>`):s}</span><button class="sentence-action" data-play-sentence="${i}" title="播放句子" aria-label="播放第 ${i+1} 句">${icon('volume-2')}</button></p>`).join('')}</div><div class="article-end row between"><span class="muted"><small>读完了，看看理解得怎么样。</small></span><button class="primary" id="practice">理解练习 ${icon('arrow-right')}</button></div></div>`}
function vocabulary(){return `<div class="eyebrow">WORDS TO KEEP</div><h1>我的生词</h1><p class="muted" style="margin-top:10px">在阅读中遇见，在复习中记住。</p><div class="list">${saved.size?[...saved].map(([key,item])=>{const definition=lessons[item.language].word[item.word]?.[2]||item.definition||'已记录，联网后补充释义';return `<div class="vocab-item"><div><strong>${escapeHtml(item.word)}</strong><p>${lessons[item.language].name} · ${escapeHtml(definition)}</p></div><button class="icon" data-remove="${escapeHtml(key)}" title="这个词我会" aria-label="移除 ${escapeHtml(item.word)}">${icon('check')}</button></div>`}).join(''):`<div class="empty">还没有生词。<br>今天读到的陌生单词，会留在这里。</div><button class="primary" data-read="de">去读今日德语 ${icon('arrow-right')}</button>`}</div>`}
function settings(){return `<div class="settings"><div class="eyebrow">YOUR OWN RHYTHM</div><h1>学习设置</h1><p class="muted" style="margin-top:10px">按自己的节奏，安排每一天。</p><div class="setting"><div>准备每日内容<p>保留未完成的文章</p></div><input type="time" aria-label="内容准备时间" value="05:00" data-setting="prepare"></div><div class="setting"><div>早间提醒<p>跟随手机所在地时区</p></div><input type="time" aria-label="早间提醒时间" value="08:00" data-setting="morning"></div><div class="setting"><div>晚间重复提醒<p>持续至两种语言完成</p></div><input type="time" aria-label="晚间提醒时间" value="22:00" data-setting="evening"></div><div class="setting"><div>重复间隔<p>分钟</p></div><input type="number" min="1" max="180" aria-label="提醒间隔分钟" value="15" data-setting="interval"></div><div class="setting"><div>每种语言学习时长<p>分钟 / 每次</p></div><input type="number" min="5" max="60" aria-label="每日学习时长" value="15" data-setting="duration"></div><div class="setting"><div>德语音色</div><select class="voice-select" data-voice="de" aria-label="德语音色"></select><button class="icon" data-preview-voice="de" aria-label="试听德语" title="试听德语">${icon("volume-2")}</button></div><div class="setting"><div>英式英语音色</div><select class="voice-select" data-voice="en" aria-label="英式英语音色"></select><button class="icon" data-preview-voice="en" aria-label="试听英语" title="试听英语">${icon("volume-2")}</button></div><div class="setting"><div>学习数据<p>保存在本机 · 未启用云同步</p></div></div><p class="muted" style="font-size:12px;margin-top:20px">当前时区：${Intl.DateTimeFormat().resolvedOptions().timeZone}</p></div>`}
const settingValues=JSON.parse(localStorage.getItem('daily-page-settings')||'{}');
let speechToken=0;
function availableVoices(lang){
  const voices=window.speechSynthesis?.getVoices()||[],locale=lessons[lang].lang.toLowerCase();
  return voices.filter(v=>v.lang.replace('_','-').toLowerCase()===locale).sort((a,b)=>Number(/premium|enhanced|natural|neural/i.test(b.name))-Number(/premium|enhanced|natural|neural/i.test(a.name)));
}
function populateVoices(){
  document.querySelectorAll('[data-voice]').forEach(select=>{
    const lang=select.dataset.voice;select.replaceChildren(new Option('自动选择系统音色',''));
    for(const voice of availableVoices(lang))select.add(new Option(voice.name,voice.voiceURI));
    select.value=settingValues['voice-'+lang]||'';
  });
}
window.speechSynthesis?.addEventListener('voiceschanged',populateVoices);
document.addEventListener('change',e=>{if(e.target.dataset.voice){settingValues['voice-'+e.target.dataset.voice]=e.target.value;persist()}});
document.addEventListener('click',e=>{const lang=e.target.closest('[data-preview-voice]')?.dataset.previewVoice;if(lang){stopAudio();language=lang;speak(lang==='de'?'Guten Morgen. Heute lernen wir Deutsch.':'Good morning. Let us read something together.')}});
function persist(){localStorage.setItem('daily-page-vocab',JSON.stringify([...saved]));localStorage.setItem('daily-page-settings',JSON.stringify(settingValues));DailyStore.save().catch(()=>{})}
// Preview definitions cover both fixture articles; production lookups will use the clicked context.
const previewMeanings={
de:{heute:'今天',steht:'起身；这里与句末 auf 构成 steht auf（起床），原形 aufstehen',lena:'莱娜，人名',früh:'早；早早地',auf:'可分动词 aufstehen 的前缀；steht ... auf 表示起床',sie:'她；指莱娜',wohnt:'居住；原形 wohnen',in:'在……里；这里表示静态位置，后接第三格',einem:'一个；不定冠词 ein 的第三格形式',kleinen:'小的；形容词 klein 的词尾变化形式',dorf:'村庄；das Dorf，复数 die Dörfer',den:'定冠词；这里是第三格复数形式',bergen:'山；der Berg，复数 die Berge；这里是第三格复数',am:'在……；an dem 的缩写，用于时间或位置',morgen:'早晨；der Morgen，复数 die Morgen',öffnet:'打开；原形 öffnen',das:'定冠词；这里修饰中性名词 Fenster',fenster:'窗户；das Fenster，复数 die Fenster',die:'定冠词；这里修饰阴性或复数名词',luft:'空气；die Luft，通常作不可数名词',ist:'是；原形 sein 的第三人称单数',frisch:'清新的',nach:'在……之后；在 nach draußen 中表示向外',dem:'定冠词；第三格阳性或中性形式',frühstück:'早餐；das Frühstück，复数 die Frühstücke',geht:'走；原形 gehen',draußen:'外面；nach draußen 表示到外面去',nimmt:'拿；这里与 mit 构成 nimmt ... mit（带上），原形 mitnehmen',ihren:'她的；这里修饰第四格阳性名词 Rucksack',rucksack:'背包；der Rucksack，复数 die Rucksäcke',mit:'可分动词 mitnehmen 的前缀；nimmt ... mit 表示带上',und:'和；并且',zum:'向……；zu dem 的缩写',see:'湖；der See，复数 die Seen',sitzt:'坐；原形 sitzen',einer:'一个；这里是不定冠词的阴性第三格形式',bank:'长椅；die Bank，复数 die Bänke',hört:'听；原形 hören',vögel:'鸟；der Vogel 的复数 die Vögel',trinkt:'喝；原形 trinken',einen:'一个；不定冠词的阳性第四格形式',tee:'茶；der Tee，复数 die Tees（不同种类的茶）',hat:'有；原形 haben',zeit:'时间；die Zeit，复数 die Zeiten',bleibt:'停留；原形 bleiben',noch:'还；再',ein:'一个；ein bisschen 是固定搭配，表示一点儿',bisschen:'一点儿；这里 noch ein bisschen 表示再待一会儿'},
en:{a:'一个；不定冠词',city:'城市；名词',can:'能；可以；情态动词',feel:'使人感觉；这里接形容词描述感受',entirely:'完全地；副词',different:'不同的；形容词',beneath:'在……下方；介词',canopy:'树冠层',of:'……的；介词',trees:'树；tree 的复数',beyond:'除了……之外；超出',their:'它们的；这里指城市树木',obvious:'显而易见的',beauty:'美；美丽',urban:'城市的',provide:'提供',something:'某种东西；某件事物',increasingly:'越来越；日益',scarce:'稀缺的',place:'地方；空间',to:'用于不定式，连接后面的动词原形',slow:'放慢；slow down 表示放慢节奏',down:'与 slow 搭配，表示放慢',shade:'树荫；阴凉处',makes:'使；make 的第三人称单数形式',crowded:'拥挤的',pavement:'人行道；英式用词',more:'更加',welcoming:'让人感到舒适、受到欢迎的',while:'而；这里连接两个相互对照的效果',leaves:'树叶；leaf 的复数',soften:'使柔和；柔化',the:'定冠词，指特定的人或事物',outline:'轮廓',buildings:'建筑物；building 的复数',yet:'然而；表转折',greener:'更绿的；这里也指绿化更好的',does:'助动词；与 not 构成一般现在时否定',not:'不；表示否定',appear:'出现；形成',overnight:'一夜之间；在很短时间内',it:'它；这里指建设更绿的城市或前文提到的树',requires:'需要；require 的第三人称单数形式',patience:'耐心',careful:'细致的；认真的',planning:'规划',and:'和；并且',sustained:'持续的',attention:'关注；注意',planting:'种植；plant 的动名词形式',tree:'树；名词',is:'是；be 的第三人称单数形式',only:'仅仅；只是',beginning:'开始；起点',keeping:'保持；keep 的动名词形式',healthy:'健康的',commitment:'承诺；需要持续投入的责任',that:'引导从句，具体作用取决于当前句子',extends:'延伸；持续，原形 extend',across:'跨越',generations:'世代；generation 的复数',perhaps:'也许',most:'最；构成最高级',valuable:'宝贵的；有价值的',thing:'事物；东西',offer:'提供',reminder:'提醒；起提醒作用的事物',progress:'进步；进展',need:'需要；need not 表示不必',always:'总是',be:'是；be 动词原形',immediate:'立即的；即时的'}
};
const originalWords={de:{...lessons.de.word},en:{...lessons.en.word}};
function makeWordsClickable(){
  const l=lessons[language],segmenter=new Intl.Segmenter(l.lang,{granularity:'word'});
  document.querySelectorAll('.sentence-row').forEach(row=>{
    const container=row.querySelector('span'),index=Number(row.dataset.sentence);
    container.replaceChildren(...Array.from(segmenter.segment(l.sentences[index]),part=>{
      if(!part.isWordLike)return document.createTextNode(part.segment);
      const button=document.createElement('button');
      button.className='word'+(part.segment===l.marked[index]?'':' plain');
      button.textContent=part.segment;button.dataset.word=part.segment;button.dataset.context=index;
      button.setAttribute('aria-label','解释 '+part.segment);
      return button;
    }));
  });
}
function prepareWord(word,index){
  const l=lessons[language];
  window.selectedWordSentence=l.sentences[index];
  if(originalWords[language][word])return;
  let meaning=previewMeanings[language][word.toLocaleLowerCase(l.lang)];
  if(language==='de'&&word.toLowerCase()==='auf'&&index===5)meaning='在……上；这里 auf einer Bank 表示静态位置，后接第三格';
  if(language==='de'&&word.toLowerCase()==='nach')meaning=index===3?'在……之后；Nach dem Frühstück 表示早餐后，后接第三格':'向；nach draußen 表示到外面去';
  if(language==='en'&&word.toLowerCase()==='it')meaning=index===3?'它；这里指建设一个绿化更好的城市':'它；这里指前文的树';
  if(language==='en'&&word.toLowerCase()==='that')meaning=index===4?'关系代词；引导定语从句，修饰 commitment':'连接词；引导同位语从句，说明 reminder 的内容';
  if(typeof courseProgress!=='undefined'&&courseProgress[language].index===1){
    meaning=nextLessons[language].meanings[word.toLocaleLowerCase(l.lang)]||previewMeanings[language][word.toLocaleLowerCase(l.lang)];
    if(language==='de'&&word.toLowerCase()==='auf')meaning='在……上；表示静态位置，后接第三格';
    if(language==='de'&&word.toLowerCase()==='ein'&&index===5)meaning='ein bisschen 表示一点儿，这里指一会儿';
    if(language==='en'&&word.toLowerCase()==='it')meaning='它；这里指社区花园';
  }
  const translation=(language==='de'?deNotes:enNotes)[index][0];
  l.word[word]=['当前语境','',meaning||'这篇示例暂未提供该词的释义。','',l.sentences[index],translation];
}
function render(){navigation();$('.global-back').disabled=page==='home';$('#main').innerHTML=page==='home'?home():page==='reader'?reader():page==='vocabulary'?vocabulary():settings();$('#crumb').textContent='学习空间 / '+({home:'今日学习',reader:'沉浸阅读',vocabulary:'我的生词',settings:'学习设置'}[page]);$('#audio-label').textContent=lessons[language].voice+' · 全文朗读';document.querySelectorAll('[data-setting]').forEach(e=>{if(settingValues[e.dataset.setting])e.value=settingValues[e.dataset.setting]});if(page==='reader'){makeWordsClickable();if(typeof courseControls==='function')courseControls()}if(page==='settings')populateVoices();window.learningRender?.();icons()}
function go(p){stopAudio();page=p;render();$('#main').scrollTo(0,0)}
function openSheet(title,html){$('#sheet-title').textContent=title;$('#sheet-body').innerHTML=html;if(!$('#sheet').open)$('#sheet').showModal();$('#sheet-body').scrollTop=0;window.learningSheet?.();icons()}
function wordSheet(word){const l=lessons[language],w=l.word[word];saved.set(language+':'+word,{language,word});navigation();openSheet('词语释义',`<div class="row between"><div><div class="dictionary-title">${word}</div><div class="phonetic">${w[1]}</div></div><button class="icon" data-speak-word="${word}" title="单词发音" aria-label="播放 ${word}">${icon('volume-2')}</button></div><p class="muted" style="font-size:12px;margin-top:15px">${w[0]}</p><p style="margin:12px 0;font-size:17px">${w[2]}</p><p class="muted" style="font-size:13px">${w[3]}</p><div class="example"><small class="muted">语境例句 · ${l.level.split(' → ')[0]}</small><p>${w[4]}</p><div class="translation" style="margin-top:6px">${w[5]}</div></div><div class="sheet-bottom"><span class="row" style="color:var(--green);font-size:13px">${icon('bookmark-check')}已加入生词</span><button class="text-btn" style="margin-left:auto" data-known="${word}">这个词我会，移除</button></div>`);stopAudio();speak(word)}
const deNotes=[['今天，莱娜早早起床。','Heute|时间状语,Lena|主语,früh|时间副词','可分动词 aufstehen 被拆成 steht 和 auf。陈述句中，变位动词 steht 放在第二位，前缀 auf 放在句末。Heute 占据第一位，所以主语 Lena 放在动词之后。','Morgen steht Lena spät auf.','明天莱娜晚起床。'],['她住在山间的一个小村庄。','','Sie 是主语，wohnt 是动词。in einem kleinen Dorf 表示静态位置，用第三格；in den Bergen 也表示位置，Bergen 是第三格复数。','Ich wohne in einer kleinen Stadt.','我住在一个小城市。'],['早上，她打开窗户。空气很清新。','','Am Morgen 是句首的时间状语。动词 öffnet 仍在第二位，因此主语 sie 跟在动词后面。das Fenster 是第四格宾语。','Am Abend öffne ich das Fenster.','晚上我打开窗户。'],['早餐后，她走到外面。','','Nach dem Frühstück 是时间状语。nach 后接第三格，所以用 dem Frühstück。geht 在第二位，主语 sie 随后；nach draußen 表示去到外面。','Nach der Arbeit gehe ich nach Hause.','下班后我回家。'],['她带上背包，走向湖边。','','mitnehmen 是可分动词：nimmt 位于第二位，mit 位于分句末尾。ihren Rucksack 是第四格宾语。und 连接两个动作；zum 是 zu dem 的缩写。','Ich nehme meine Tasche mit.','我带上我的包。'],['她坐在湖边的长椅上，听着鸟鸣，喝着茶。','','Am See 表示位置，在句首占据第一位，因此变位动词 sitzt 后面才是主语 sie。auf einer Bank 描述静态位置，用第三格。','Im Park sitzt er auf einer Bank.','他坐在公园里的长椅上。'],['今天莱娜有时间。她再待一会儿。','','Heute 占第一位，变位动词 hat 放第二位，主语 Lena 在后面。第二句中 Sie 是主语，bleibt 是动词，noch ein bisschen 表示再一会儿。','Heute habe ich Zeit.','今天我有时间。']];
const enNotes=[['在树冠的遮蔽下，一座城市会让人感到截然不同。','A city 是主语；can feel 是情态动词加感官动词；entirely different 描述感受；beneath a canopy of trees 是介词短语。'],['除了显而易见的美，城市树木还提供了一种日益稀缺的东西：让人慢下来的空间。','Beyond 引出补充视角。something increasingly scarce 中，形容词短语置于不定代词 something 之后；冒号进一步解释具体指什么。'],['树荫让拥挤的人行道更亲切，树叶则柔化了建筑的轮廓。','make + 宾语 + 动词原形：makes a crowded pavement feel ...。while 在这里连接两个并列对照的效果。'],['然而，更绿的城市不是一夜之间出现的。它需要耐心、细致规划和持续关注。','Yet 表转折。appear overnight 指短时间内出现；patience、careful planning 和 sustained attention 构成并列宾语。'],['种树仅仅是开始；保持它健康是一项跨越世代的承诺。','Planting a tree 和 keeping it healthy 是动名词短语，分别充当主语。that 引导定语从句，修饰 commitment。'],['也许树木最宝贵的价值，是提醒我们：进步不必总是立刻发生。','trees offer 是省略关系代词的定语从句，修饰 thing。that 引导同位语从句，说明 reminder 的内容；need not 表示不必。']];
let analyzed=0;
function analysis(i,tab='structure'){analyzed=i;activeTab=tab;const l=lessons[language],n=language==='de'?deNotes[i]:enNotes[i];let content='';if(tab==='structure'){content=language==='de'&&i===0&&lessons[language].title==='Ein Morgen in den Bergen'?`<div class="structure"><div class="part">Heute<small>① 时间状语</small></div><div class="part">steht<small>② 变位动词</small></div><div class="part">Lena<small>主语</small></div><div class="part">früh auf<small>时间 + 动词前缀</small></div></div><div class="explain"><strong>为什么是这个顺序？</strong><p>${n[2]}</p><div class="note"><strong>Heute</strong> | <strong>steht</strong> | Lena früh | <strong>auf.</strong><br>第一位可以变化，变位动词仍在第二位。</div></div>`:`<div class="explain"><strong>${language==='de'?'理解这句话的结构':'Sentence structure'}</strong><p>${language==='de'?n[2]:n[1]}</p></div>`}else if(tab==='examples'){content=`<div class="example" style="border:0;margin:0;padding:0"><small class="muted">相同结构，再读一句</small><p>${language==='de'?n[3]:(n[2]||'A familiar street can feel entirely different in the rain.')}</p><div class="translation">${language==='de'?n[4]:(n[3]||'一条熟悉的街道，在雨中可能让人感觉截然不同。')}</div></div>`}else{content=`<div class="explain"><strong>这句话的学习重点</strong><p>${language==='de'?n[2]:n[1]}</p><div class="note">${language==='de'?'先找变位动词，再找主语，最后理解时间、地点和其他成分。':'先找到主句，再理解修饰语如何补充信息。'}</div></div>`}openSheet('句子解析',`<small class="muted">${l.native} · 第 ${i+1} 句</small><div class="quote">${l.sentences[i]}</div><p class="translation">${n[0]}</p><div class="analysis-tabs" role="tablist">${[['structure','句子结构'],['examples','同类例句'],['notes','学习重点']].map(([t,label])=>`<button role="tab" aria-selected="${tab===t}" data-tab="${t}" class="${tab===t?'active':''}">${label}</button>`).join('')}</div>${content}<div class="sheet-bottom"><button class="secondary" data-speak-sentence="${i}">${icon('volume-2')}听这句话</button><button class="primary" data-next-analysis="${(i+1)%l.sentences.length}">下一句 ${icon('arrow-right')}</button></div>`)}
function practice(){if(typeof courseProgress!=='undefined'&&courseProgress[language].index===1){const l=nextLessons[language];openSheet('阅读理解',`<h2>${l.question}</h2>${l.choices.map((s,i)=>`<button class="question-choice" data-answer="${i}">${String.fromCharCode(65+i)}. ${s}</button>`).join('')}<div id="feedback" class="feedback" role="status"></div>`);return;}openSheet('阅读理解',`<div class="eyebrow">CHECK YOUR UNDERSTANDING</div><h2>${language==='de'?'Lena geht nach dem Frühstück ...':'What does the article emphasise about urban trees?'}</h2><div style="margin-top:20px">${(language==='de'?['nach draußen.','zur Arbeit.','ins Kino.']:['They require long-term care.','They grow fully overnight.','They only improve appearance.']).map((s,i)=>`<button class="question-choice" data-answer="${i}">${String.fromCharCode(65+i)}. ${s}</button>`).join('')}</div><div id="feedback" class="feedback" role="status"></div>`)}
function stopAudio(){speechToken++;window.CloudSpeech?.stop();if('speechSynthesis'in window)speechSynthesis.cancel();playing=false;document.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'));$('#play').innerHTML=icon('play');$('#play').setAttribute('aria-label','播放文章');icons()}
function systemSpeak(text,onend){if(!('speechSynthesis'in window)){toast('当前设备不支持语音播放');return}const token=speechToken,l=lessons[language],u=new SpeechSynthesisUtterance(text);u.lang=l.lang;u.rate=Number($('#speed').value);const voices=availableVoices(language),selected=settingValues['voice-'+language];u.voice=voices.find(v=>v.voiceURI===selected)||voices[0]||null;u.onend=()=>{if(token!==speechToken)return;if(onend)onend();else stopAudio()};u.onerror=e=>{if(token!==speechToken||e.error==='canceled'||e.error==='interrupted')return;stopAudio();toast('语音未能播放，请检查系统语音设置')};speechSynthesis.speak(u)}
function speak(text,onend){if(window.CloudSpeech&&settingValues.speechMode==='cloud')return CloudSpeech.speak(text,onend);return systemSpeak(text,onend)}
function playSentence(i,continuous=false){stopAudio();sentenceIndex=i;playing=true;$('#play').innerHTML=icon('square');$('#play').setAttribute('aria-label','停止播放');const row=$(`[data-sentence="${i}"]`);if(row)row.classList.add('speaking');$('#audio-label').textContent=lessons[language].voice+' · 第 '+(i+1)+' 句';$('#audio-progress').style.width=((i+1)/lessons[language].sentences.length*100)+'%';icons();speak(lessons[language].sentences[i],()=>{if(continuous&&i+1<lessons[language].sentences.length)playSentence(i+1,true);else stopAudio()})}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b){if(b.dataset.nav){go(b.dataset.nav);return}if(b.dataset.read){language=b.dataset.read;sentenceIndex=0;go('reader');return}if(b.dataset.word){prepareWord(b.dataset.word,Number(b.dataset.context));wordSheet(b.dataset.word);return}if(b.dataset.analyze!==undefined){analysis(Number(b.dataset.analyze));return}if(b.dataset.tab){analysis(analyzed,b.dataset.tab);return}if(b.dataset.nextAnalysis!==undefined){analysis(Number(b.dataset.nextAnalysis));return}if(b.dataset.speakSentence!==undefined){playSentence(Number(b.dataset.speakSentence));return}if(b.dataset.speakWord){stopAudio();speak(b.dataset.speakWord);return}if(b.dataset.known){saved.delete(language+':'+b.dataset.known);$('#sheet').close();navigation();icons();toast('已从生词中移除');return}if(b.dataset.remove){saved.delete(b.dataset.remove);render();return}if(b.dataset.answer!==undefined){document.querySelectorAll('.question-choice').forEach(c=>c.classList.toggle('selected',c===b));$('#feedback').textContent=b.dataset.answer==='0'?'回答正确。你抓住了文章的关键信息。':'再想一想，也可以回到文章中找找线索。';return}if(b.id==='practice'){practice();return}}
const s=e.target.closest('.sentence-row');if(s)analysis(Number(s.dataset.sentence))});
document.addEventListener('change',e=>{if(e.target.dataset.setting){if(e.target.checkValidity()){settingValues[e.target.dataset.setting]=e.target.value;persist();toast('设置已保存')}else e.target.reportValidity()}});
document.addEventListener('click',e=>{const button=e.target.closest('[data-play-sentence]');if(button){e.stopPropagation();playSentence(Number(button.dataset.playSentence));return}} ,true);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&b.dataset.word){const item=saved.get(language+':'+b.dataset.word);if(item)item.definition=lessons[language].word[b.dataset.word]?.[2];}if(b&&(b.dataset.word||b.dataset.known||b.dataset.remove))persist()});
$('#close-sheet').onclick=()=>$('#sheet').close();$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet')){const r=$('#sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#sheet').close()}});$('#play').onclick=()=>playing?stopAudio():playSentence(sentenceIndex,true);$('#audio-next').onclick=()=>playSentence((sentenceIndex+1)%lessons[language].sentences.length);$('#speed').onchange=()=>{if(window.CloudSpeech?.active)CloudSpeech.setRate(Number($('#speed').value));else if(playing)playSentence(sentenceIndex,false)};
$('#date').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
render();
